/**
 * report.js — Render comparison results as a client-ready markdown report
 *
 * The report is written to be pasted into a client doc: a priority-ordered
 * regression list with the exact old and new strings, so the copy owner can
 * approve a specific edit rather than a vague recommendation.
 */

const SEVERITY_BADGE = { high: 'HIGH', medium: 'MED', low: 'LOW' };

/** Escape pipes so long copy strings do not break markdown tables. */
function cell(value, max = 120) {
  if (value === null || value === undefined || value === '') return '_(none)_';
  const str = String(value).replace(/\|/g, '\\|').replace(/\n/g, ' ');
  return str.length > max ? `${str.slice(0, max - 1)}…` : str;
}

/**
 * @param {object[]} results - from compareSite
 * @param {object} summary - from summarise
 * @param {object} site - site config
 * @returns {string} markdown
 */
function renderMarkdown(results, summary, site) {
  const date = new Date().toISOString().slice(0, 10);
  const L = [];

  L.push(`# Entity signal audit — ${site.entity}`);
  L.push('');
  L.push(`**Old site:** ${site.old.origin}  `);
  L.push(`**Current site:** ${site.current.origin}  `);
  L.push(`**Generated:** ${date}`);
  L.push('');
  L.push('Compares entity signals page by page between the previous site and the current one, to');
  L.push('identify which signals were lost in the redesign. Generated by `tools/entity-audit`.');
  L.push('');

  // --- Summary ------------------------------------------------------------
  L.push('## Summary');
  L.push('');
  L.push('| Metric | Count |');
  L.push('| --- | --- |');
  L.push(`| Pages compared | ${summary.pagesCompared} |`);
  L.push(`| Pages with regressions | ${summary.pagesRegressed} |`);
  L.push(`| Pages unchanged | ${summary.pagesOk} |`);
  L.push(`| Pages improved | ${summary.pagesImproved} |`);
  L.push(`| New pages (no old equivalent) | ${summary.pagesNew} |`);
  L.push(`| Dropped pages | ${summary.pagesDropped} |`);
  L.push(`| **Total regressions** | **${summary.totalRegressions}** |`);
  L.push(`| — high severity | ${summary.bySeverity.high || 0} |`);
  L.push(`| — medium severity | ${summary.bySeverity.medium || 0} |`);
  L.push(`| — low severity | ${summary.bySeverity.low || 0} |`);
  L.push('');

  // --- Regressions by type -------------------------------------------------
  const kinds = Object.entries(summary.byKind).sort((a, b) => b[1] - a[1]);
  if (kinds.length) {
    L.push('## Regressions by type');
    L.push('');
    L.push('| Signal lost | Pages affected |');
    L.push('| --- | --- |');
    for (const [kind, count] of kinds) L.push(`| \`${kind}\` | ${count} |`);
    L.push('');
  }

  // --- Signal score table --------------------------------------------------
  L.push('## Entity signal score by page');
  L.push('');
  L.push('Higher is stronger. Score weights title, H1, factual statements and Person schema most heavily.');
  L.push('');
  L.push('| Page | Old | Current | Change | Status |');
  L.push('| --- | ---: | ---: | ---: | --- |');
  for (const r of results) {
    const o = r.old ? r.old.signalScore : null;
    const c = r.current ? r.current.signalScore : null;
    const delta = o !== null && c !== null ? (c - o).toFixed(2) : '—';
    const arrow = o !== null && c !== null ? (c < o ? ' ↓' : c > o ? ' ↑' : '') : '';
    L.push(`| ${cell(r.name || r.slug)} | ${o ?? '—'} | ${c ?? '—'} | ${delta}${arrow} | ${r.status} |`);
  }
  L.push('');

  // --- Page detail ---------------------------------------------------------
  L.push('## Page-by-page detail');
  L.push('');

  const regressed = results.filter((r) => r.regressions.length);
  const clean = results.filter((r) => !r.regressions.length);

  for (const r of regressed) {
    L.push(`### ${r.name || r.slug}`);
    L.push('');
    L.push(`- Old: \`${r.oldUrl || '—'}\``);
    L.push(`- Current: \`${r.currentUrl || '—'}\``);
    L.push('');
    L.push('| Sev | Signal | Old | Current |');
    L.push('| --- | --- | --- | --- |');
    for (const reg of r.regressions) {
      L.push(
        `| ${SEVERITY_BADGE[reg.severity]} | ${cell(reg.label)} | ${cell(reg.oldValue)} | ${cell(reg.newValue)} |`,
      );
    }
    L.push('');

    const withDetail = r.regressions.filter((reg) => reg.detail && reg.detail.length);
    if (withDetail.length) {
      L.push('<details><summary>Detail</summary>');
      L.push('');
      for (const reg of withDetail) {
        L.push(`**${reg.label}** — lost:`);
        L.push('');
        for (const d of reg.detail) L.push(`- ${cell(d, 300)}`);
        L.push('');
      }
      L.push('</details>');
      L.push('');
    }

    if (r.gains.length) {
      L.push(`_Also improved: ${r.gains.map((g) => g.label).join(', ')}._`);
      L.push('');
    }
  }

  if (clean.length) {
    L.push('### Pages with no regressions');
    L.push('');
    for (const r of clean) {
      L.push(`- **${r.name || r.slug}** — ${r.status}${r.gains.length ? ` (gained: ${r.gains.map((g) => g.label).join(', ')})` : ''}`);
    }
    L.push('');
  }

  // --- Current-site entity snapshot ---------------------------------------
  L.push('## Current site — entity signal snapshot');
  L.push('');
  L.push('| Page | Title has name | H1 has name | Desc has name | Factual stmts | Mentions | JSON-LD |');
  L.push('| --- | :-: | :-: | :-: | ---: | ---: | --- |');
  for (const r of results) {
    if (!r.current) continue;
    const c = r.current;
    const yn = (b) => (b ? 'yes' : 'NO');
    L.push(
      `| ${cell(r.name || r.slug)} | ${yn(c.titleHasEntity)} | ${yn(c.h1HasEntity)} | ${yn(c.descriptionHasEntity)} | ${c.factualStatements.length} | ${c.entityMentions} | ${c.jsonLdTypes.length ? c.jsonLdTypes.join(', ') : '_none_'} |`,
    );
  }
  L.push('');

  // --- H1 reference --------------------------------------------------------
  L.push('## H1 comparison (old vs current)');
  L.push('');
  L.push('| Page | Old H1 | Current H1 |');
  L.push('| --- | --- | --- |');
  for (const r of results) {
    const oldH1 = r.old ? (r.old.h1s || []).join(' / ') : null;
    const newH1 = r.current ? (r.current.h1s || []).join(' / ') : null;
    L.push(`| ${cell(r.name || r.slug)} | ${cell(oldH1)} | ${cell(newH1)} |`);
  }
  L.push('');

  L.push('---');
  L.push('');
  L.push('**Note on copy ownership:** these are diagnostic findings, not approved copy.');
  L.push("Final wording sits with the client's team.");
  L.push('');

  return L.join('\n');
}

export { renderMarkdown };
